dist: trusty
sudo: false

language: node_js
node_js:
  - "10"
cache: npm

before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless

build:
  script: ng build --prod
  branches:
    only:
    - develop
    - master

# before_deploy:
#   - ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/dung1764
  on:
    branch: master
